# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9700afa178cc32952143c9bb3d3821dbe5ac80c1a2bbdf153c2ff5bb2830642840fea9c929f8b84c15690e4a86b3a627e6998d2bd5840a75c608a4d7525e23d8

test:
  secret_key_base: c3cabf3ef6aa4ef1a12948c17517f8c26ff86058c6525c4d963e421b03272569a87716d4e73be48e9fa2b808b95031a6d4adbdb76a0e947c8eefb4d9a698d6cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
